config/routes.rb
CleanTweets::Application.routes.draw do

  root to: 'users#new'
  resources :users, only:[:index,:new,:create,:edit,:destroy,:update]
  get "users/stream" => "users#stream", as: "stream_user"

  resources :fav_tweets, only:[:index, :new, :destroy]
  get "auth/twitter" => "fav_tweets#show_tweets", as: "twitter_auth"
  get "fav_tweets/show_tweets" => "fav_tweets#show_tweets", as: "show_tweets"
  post "fav_tweets" => "fav_tweets#create", as: "create_fav_tweet"
  get "fav_tweets/display" => "fav_tweets#display", as: "display_fav_tweet"
  get "fav_tweets/favorites" => "fav_tweets#favorites", as: "favorites_fav_tweet"
  delete "fav_tweets/favorites/:tweet_id" => "fav_tweets#delete_favorite", as: "delete_favorite"

  
  delete "auths" => "auths#destroy", as: "auths"
  resources :auths, only:[:new, :create]

  match "/auth/twitter/callback" => "fav_tweets#get_user_data", via: [:get, :post]

end

app/models/user.rb
require 'bcrypt'

class User
	include Mongoid::Document

	attr_accessor :password	

	field :name, type: String
	field :username, type: String
	field :email, type: String
	field :salt, type: String
	field :hashed_password, type: String
	field :access_token, type: String
	field :access_token_secret, type: String

	has_and_belongs_to_many :fav_tweets

	def authenticated? pwd
	  	self.hashed_password ==
	  	  BCrypt::Engine.hash_secret(pwd, self.salt)
	end

	def from_omniauth(auth)
		# auth = request.env['omniauth.auth']
		self.username = auth["info"]["nickname"]
		self.name = auth["info"]["name"]
		self.access_token = auth["credentials"]["token"]
		self.access_token_secret = auth["credentials"]["secret"]
		save!
		self
	end

	def twitter
		@twitter ||= Twitter::REST::Client.new do |config|
		  config.consumer_key        = "EGtAiRXlnFzX90MPtkHA"
		  config.consumer_secret     = "OkDiA6C0Ej2yBg9Jh6Rdhoxc25b5aMfQLRwbY1Mw0U"
		  config.access_token        = access_token
		  config.access_token_secret = access_token_secret
		end
	end 

	before_save :hash_the_password

	private 

	def hash_the_password
		unless self.password == nil
  		self.salt = BCrypt::Engine.generate_salt
  		self.hashed_password = BCrypt::Engine.hash_secret self.password, self.salt
  		self.password = nil
  	end
	end	
end

app/controllers/users_controller.rb
require 'yaml'

class UsersController < ApplicationController
  
  def index
  	@users = User.all
  end

  def new
    if current_user
      redirect_to twitter_auth_path
      flash[:notice] = "current_user was true"
    else
      @user = User.new
    end
  end

  def create
    if !(User.where(email: user_params[:email]).empty?)
      flash[:notice] = "This email already exists"
      redirect_to new_user_path(user_params)
    else
      @user = User.create(user_params)  
      flash[:notice] = "you signed up. Your email is #{params[:user][:email]}."
      redirect_to new_auth_path(user_params)
    end  
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.update(user_params)
  	redirect_to users_path
  end	

  def destroy
  	@user = User.find(params[:id])
  	@user.destroy
  	redirect_to users_path
  end

  def welcome
    current_user.from_omniauth(request.env['omniauth.auth'])
    # raise request.env['omniauth.auth'].to_yaml
  end   


  private 

  def user_params 
  	params.require(:user).permit(:email, :password)
  end		
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Edit Your Info</h1>

<%= form_for @user do |u| %>
	<div>
		<%= u.label :email %>
	</div>

	<div>
		<%= u.text_field :email, :place_holder=> "What's your email" %>
	</div>

	<div>
		<%= u.label :password %>
	</div>

	<div>
		<%= u.password_field :password, :place_holder=>"Create a Password" %>
	</div>

	<div>
		<%= u.submit %>
	</div>	

<% end %>		

app/views/users/index.html.erb
<h1>Index of All Clean Tweet Users</h1>
<p id='notice'> <%= notice %></p>

<table>
	<tr>
		<th>Name</th>
		<th>Username</th>
		<th>Email</th>
		<th>Edit</th>
	</tr>
	<% @users.each do |u| %>
	<tr>
		<td> <%= u.name %> </td>
		<td> <%= u.username %> </td>
		<td> <%= u.email %> </td>
		<td> <%= link_to "Edit", edit_user_path(u) %> </td>
		<td> <%= link_to "Delete", user_path(u), method: 'delete' %> </td>
	</tr>
	<% end %>
</table>

<br />
<br />
<br />

<%= button_to "Log Out", auths_path, method: 'delete' %>

app/views/users/new.html.erb
<span class="hide_mobile"><%= render "layouts/navbar" %></span>
<%= notice %>


<div class="container-fluid">
<%= form_for @user do |u| %>

	<div class="row main">
		<div class=" col-xs-12 col-md-7 col-md-push-5 description">
			<!-- only shows on mobile view (navbar is also removed) -->
			<% if params[:controller] == "auths" || params[:controller] == "users" %>
      	<%=link_to get_page, get_route, class:"btn show_mobile mobile_login" %>
    	<% end %>
			<h1 class="headline">Clean Tweets</h1>
			<h2 class="tagline">Read What Matters</h2>

			<div class="row form">
				<div class="col-xs-0 col-md-2"></div>
				<div class="col-xs-12 col-md-8">
					<div>
						<%= u.label :email %>
						<%= u.text_field :email, :placeholder=> "What's your email", class: "form-control" %>
					</div>

					<div class="password_container">
						<%= u.label :password %>
						<%= u.password_field :password, :placeholder=>"Create a Password", class: "form-control" %>
					</div>

					<div class="centered">
						<%= u.submit 'Sign up', class: "btn submit" %>
					</div>
				</div>
				<div class="col-xs-0 col-md-2"></div>	
			</div>

		</div>
		<div class="col-xs-12 col-md-5 col-md-pull-7"><i class="fa fa-twitter"></i></div>
	</div>		
</div>
<% end %>

app/views/users/welcome.html.erb
<h1>Welcome</h1>

<pre><%= request.env['omniauth.auth'].to_yaml %></pre>