config/routes.rb
CleanTweets::Application.routes.draw do

  root to: 'users#new'
  resources :users, only:[:index,:new,:create,:edit,:destroy,:update]
  get "users/stream" => "users#stream", as: "stream_user"

  resources :fav_tweets, only:[:index, :new, :destroy]
  get "auth/twitter" => "fav_tweets#show_tweets", as: "twitter_auth"
  get "fav_tweets/show_tweets" => "fav_tweets#show_tweets", as: "show_tweets"
  post "fav_tweets" => "fav_tweets#create", as: "create_fav_tweet"
  get "fav_tweets/display" => "fav_tweets#display", as: "display_fav_tweet"
  get "fav_tweets/favorites" => "fav_tweets#favorites", as: "favorites_fav_tweet"
  delete "fav_tweets/favorites/:tweet_id" => "fav_tweets#delete_favorite", as: "delete_favorite"

  
  delete "auths" => "auths#destroy", as: "auths"
  resources :auths, only:[:new, :create]

  match "/auth/twitter/callback" => "fav_tweets#get_user_data", via: [:get, :post]

end

app/models/fav_tweet.rb
class FavTweet
  include Mongoid::Document
  field :tweet_id, type: Integer
  field :text, type: String
  field :username, type: String

  has_and_belongs_to_many :users


  def self.filter_tweets(ht)
    filtered_tweets = []

    ht.each do |tweet|
      # find number of link
      num_links = tweet[:text].scan("http").length
      if num_links > 0 
        # if a tweets only link isnt from a picture or if the tweet has more
        # than one link then the tweet passes
        if tweet.attrs[:entities][:media] == nil || num_links > 1
          filtered_tweets << tweet
        end
      end
    end
    return filtered_tweets
  end


  def self.rank_tweets(tweets)
    tweets.each do |tweet|
      retweet_count = tweet.attrs[:retweet_count]
      # validate that a tweet is not a retweet
      if tweet.attrs[:retweeted_status] == nil
        favorite_count = tweet.attrs[:favorite_count]
      else
        favorite_count = tweet.attrs[:retweeted_status][:favorite_count]
      end
      rank = retweet_count + favorite_count
      tweet.attrs[:rank] = rank 
    end
    return tweets
  end

  def self.sort_tweets(ranked_tweets)
    ranked_tweets.sort_by!{|tweet| -tweet.attrs[:rank]}
  end

end

app/models/user.rb
require 'bcrypt'

class User
	include Mongoid::Document

	attr_accessor :password	

	field :name, type: String
	field :username, type: String
	field :email, type: String
	field :salt, type: String
	field :hashed_password, type: String
	field :access_token, type: String
	field :access_token_secret, type: String

	has_and_belongs_to_many :fav_tweets

	def authenticated? pwd
	  	self.hashed_password ==
	  	  BCrypt::Engine.hash_secret(pwd, self.salt)
	end

	def from_omniauth(auth)
		# auth = request.env['omniauth.auth']
		self.username = auth["info"]["nickname"]
		self.name = auth["info"]["name"]
		self.access_token = auth["credentials"]["token"]
		self.access_token_secret = auth["credentials"]["secret"]
		save!
		self
	end

	def twitter
		@twitter ||= Twitter::REST::Client.new do |config|
		  config.consumer_key        = "EGtAiRXlnFzX90MPtkHA"
		  config.consumer_secret     = "OkDiA6C0Ej2yBg9Jh6Rdhoxc25b5aMfQLRwbY1Mw0U"
		  config.access_token        = access_token
		  config.access_token_secret = access_token_secret
		end
	end 

	before_save :hash_the_password

	private 

	def hash_the_password
		unless self.password == nil
  		self.salt = BCrypt::Engine.generate_salt
  		self.hashed_password = BCrypt::Engine.hash_secret self.password, self.salt
  		self.password = nil
  	end
	end	
end

app/controllers/fav_tweets_controller.rb
class FavTweetsController < ApplicationController
	
	def index
	end

	def new
	end

	def destroy
	end

	def get_user_data
		current_user.from_omniauth(request.env['omniauth.auth'])
		redirect_to show_tweets_path
	end 	

	def show_tweets
		# current_user.from_omniauth(request.env['omniauth.auth'])
		
		ht = current_user.twitter.home_timeline(count: 200)
		## filter out tweets that don't have a link, or tweets
		# whose only link is from a picture
		filtered_tweets = FavTweet.filter_tweets(ht)
		# home_timeline = ht.find_all {|tweet| tweet.text.include?("http")}
		ranked_tweets = FavTweet.rank_tweets(filtered_tweets)
		@sorted_tweets = FavTweet.sort_tweets(ranked_tweets)
	end

	def create
		## if that tweet was never created then create and add it to current user's fav_tweets
		if FavTweet.all.where(tweet_id: params[:format]).empty?
			@fav_tweet = FavTweet.create(tweet_id: params[:format])
			current_user.fav_tweets << @fav_tweet
		## if the tweet was created, check if exists in current_user's fav_tweets	
		elsif check_fav_tweets(params[:format]) == true
				flash[:notice] = "You already favorited that tweet"
		else
			## if the tweet doesn't exist in the current_user's fav_tweets then add it.
			@fav_tweet = FavTweet.all.find_by(tweet_id: params[:format])
			current_user.fav_tweets << @fav_tweet
		end	 
		redirect_to show_tweets_path
	end

	def favorites
		@fav_tweets = current_user.fav_tweets
		@fav_tweet_ids = @fav_tweets.map { |tweet| tweet.tweet_id}
	end

	def delete_favorite
		cu = current_user
		tw = FavTweet.find_by(tweet_id: params[:tweet_id])
		cu.fav_tweet_ids -= [tw.id]
		tw.user_ids -= [cu.id]
		cu.save
		tw.save
		redirect_to favorites_fav_tweet_path
	end	

	private 

	def fav_tweet_params 
		params.require(:fav_tweet).permit(:username, :text, :id)
	end

	def check_fav_tweets(tweet_id)
		current_user.fav_tweets.each do |tweet|
			if tweet.tweet_id == tweet_id
				return true
			end
		end	
	end	

end

app/helpers/fav_tweets_helper.rb
module FavTweetsHelper

  def add_link(tweet)
    new_text = tweet.text.dup
    num_links = tweet[:text].scan("http").length
    iterator = 1
    idx = 0
    # loop through all all links and add them to the tweet.text
    while iterator <= num_links do 
      start = new_text.index("http", idx)
      # find index of white space or use the length of the text
      last = new_text.index(/\s/, start) || new_text.length
      link = new_text.slice!(start..last)
      # if the tweet has pics and we are iterating over the last
      # link, which is always the pic, then we should link to the urls
      # for the image of the pic, else, link to the appropriate url. 
      if tweet.attrs[:entities][:media] != nil && num_links == iterator
        new_text = new_text.insert(start, "#{link_to link, tweet.attrs[:entities][:media].first[:media_url_https] }" )
      else
        new_text = new_text.insert(start, "#{link_to link, tweet.attrs[:entities][:urls][iterator-1][:expanded_url] }" )
      end
      end_of_link = new_text.index("</a>", idx)
      idx = end_of_link + 4
      iterator += 1
    end
    return new_text
  end
end

app/views/fav_tweets/favorites.html.erb
<%= render "layouts/navbar" %>

<h1>Look at Your Favorite Tweets</h1>

<div class="container-fluid show_tweets_container">
  <div class="row">
    <div class="col-md-3 col-sm-3 col-xs-1"></div>
    <div class="col-md-6 col-sm-6 col-xs-10 time_line">
    	<% @fav_tweet_ids.each do |id| %>

        <div class="tweet_shell">
          <div class="tweet">
            <!-- <div><#%= id %></div> -->
          	<div class="user_name"><%=link_to "@"+current_user.twitter.status(id).user.user_name,"http://www.twitter.com/"+current_user.twitter.status(id).user.user_name %>
            </div>
            <div>
              <%= link_to raw("<span class='glyphicon glyphicon-remove'></span>"), delete_favorite_path(id), method: 'delete', class:'btn_favorite' %>
            </div>  
          	<div class="text"><%= current_user.twitter.status(id).text %></div>
          </div>
        </div>

      <% end %>    
    </div>  
    <div class="col-md-3 col-sm-3 col-xs-1"></div>
</div>

app/views/fav_tweets/index.html.erb
<h1>FavTweets#index</h1>
<p>Find me in app/views/fav_tweets/index.html.erb</p>

app/views/fav_tweets/show_tweets.html.erb
<%= render "layouts/navbar" %>

<%#= "hello" link_to "hi", "http://www.heatandcoolaz.com" %> 
<div class="container-fluid show_tweets_container">
	<div class="row">
		<div class="col-md-3 col-sm-3 col-xs-1"></div>
		<div class="col-md-6 col-sm-6 col-xs-10 time_line">
			<% @sorted_tweets.each do |tweet| %>

				<div class="tweet_shell">
					<div class="tweet">
						<div class="user_name"><%=link_to "@"+tweet.user.user_name, "http://www.twitter.com/" + tweet.user.user_name, class:'user_name' %> </div>
						<div>
							<%= link_to raw("<span class='glyphicon glyphicon-heart-empty'></span>"), create_fav_tweet_path(tweet.id), method: 'post', class:'btn_favorite' %>
						</div>	
						<div>rank: <%= tweet.attrs[:rank] %> </div>
						<div>rt count: <%= tweet.attrs[:retweet_count] %> </div>
						<div>fav count: <%= tweet.attrs[:favorite_count] %> </div>
						<div class="text"> <%= raw(add_link(tweet)) %> </div>
					</div>
				</div>
					
			<% end %>
		</div>
		<div class="col-md-3 col-sm-3 col-xs-1"></div>
	</div>	
</div>