config/routes.rb
CleanTweets::Application.routes.draw do

  root to: 'users#new'
  resources :users, only:[:index,:new,:create,:edit,:destroy,:update]
  get "users/stream" => "users#stream", as: "stream_user"

  resources :fav_tweets, only:[:index, :new, :destroy]
  get "auth/twitter" => "fav_tweets#show_tweets", as: "twitter_auth"
  get "fav_tweets/show_tweets" => "fav_tweets#show_tweets", as: "show_tweets"
  post "fav_tweets" => "fav_tweets#create", as: "create_fav_tweet"
  get "fav_tweets/display" => "fav_tweets#display", as: "display_fav_tweet"
  get "fav_tweets/favorites" => "fav_tweets#favorites", as: "favorites_fav_tweet"
  delete "fav_tweets/favorites/:tweet_id" => "fav_tweets#delete_favorite", as: "delete_favorite"

  
  delete "auths" => "auths#destroy", as: "auths"
  resources :auths, only:[:new, :create]

  match "/auth/twitter/callback" => "fav_tweets#get_user_data", via: [:get, :post]

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Clean Tweets</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">

        <!-- greet user if they are signed in -->
        <% unless current_user == nil %>
          <li><a>Hi <%= current_user.name %></a></li>
        <% end %>

        <!-- if on users/new or auths/new show login or signup button -->
        <% if params[:controller] == "auths" || params[:controller] == "users" %>
          <li><%=link_to get_page, get_route, class:"btn navbar_login" %></li>
        <% end %>

        <!-- if called from fav_tweets controller show multiple options -->
        <% if params[:controller] == "fav_tweets" %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Options<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if params[:action] == "favorites" %>
                  <li><%=link_to "Clean Tweets", show_tweets_path %></li>
                <% else %>
                  <li><%=link_to "Favorites", favorites_fav_tweet_path %></li>
                <% end %>  
                <li class="divider"></li>   
                <li><%= link_to "Log Out", auths_path, method: 'delete' %></li>
              </ul>
          </li>    
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CleanTweets</title>
  <link href='http://fonts.googleapis.com/css?family=Lobster+Two:400,700,400italic' rel='stylesheet' type='text/css'>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>

<%= yield %>

</body>
</html>